### ISSUE TITLE
How should the Settings.yaml look like?

### ISSUE THREAD

**Issue by olleharstedt** [bwaidelich/Wwwision.Neos.MailChimp#4]
Hi!
I'm not sure how the settings file should look like. I've tried a couple of combinations but still get an error in the backend. Is this correct?

```
Wwwision:
  Neos:
    MailChimp:
      apiKey: 'bla'
```

Or should there be a `TYPO3` somewhere?
